FROM supplantr/toolbox

# Required to build python-language-server.
RUN dnf install -y gcc
RUN dnf install -y python-devel

RUN dnf install -y pyp2rpm

RUN pip install black
RUN pip install pylint
RUN pip install python-language-server
RUN pip install mypy

RUN pip install pipenv
