name: ci

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push toolbox
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: supplantr/toolbox:latest

      - name: Build and push ansible toolbox
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.ansible
          push: true
          tags: supplantr/ansible-toolbox:latest

      - name: Build and push golang toolbox
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.golang
          push: true
          tags: supplantr/golang-toolbox:latest

      - name: Build and push lua toolbox
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.lua
          push: true
          tags: supplantr/lua-toolbox:latest

      - name: Build and push python toolbox
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.python
          push: true
          tags: supplantr/python-toolbox:latest

      - name: Build and push shell toolbox
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.shell
          push: true
          tags: supplantr/shell-toolbox:latest
